name: pyhep2022-phasespace
channels:
  - conda-forge
dependencies:
  - pip
  - hist
  - numpy
  - pandas
  - matplotlib
  - particle
  - hepunits
  - uproot
  - pip:
    - DecayLanguage
    - phasespace==1.7.0
    - zfit~=0.10.1
    - zfit-physics~=0.2.0
